name: App Fairground
'on':
  push:
    branches:
    - main
    tags: '[0-9]+.[0-9]+.[0-9]+'
  pull_request_target:
    branches:
    - main
    types:
    - opened
    - synchronize
    - reopened
jobs:
  fork_apply:
    name: Fork Apply
    runs-on: macos-latest
    timeout-minutes: 45
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0_beta.app/Contents/Developer
    steps:
    - name: Initialize fair-ground
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: 'echo "$GITHUB_CONTEXT"

        echo "$GITHUB_CONTEXT"

        echo "ORGNAME=${{ github.repository_owner }}" >> $GITHUB_ENV

        echo "COMMITHASH=${{ github.sha }}" >> $GITHUB_ENV

        '
    - name: 'Configure Fork: ${{ env.ORGNAME }}'
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: 'echo "FAIR_APP_ARTIFACT=${{ env.ORGNAME }}" >> $GITHUB_ENV

        echo "PRODUCT_NAME=$(echo ${{ env.ORGNAME }} | tr ''-'' '' '')" >> $GITHUB_ENV

        echo "BUNDLE_ID=app.$(echo ${{ env.ORGNAME }})" >> $GITHUB_ENV

        echo "BUILDING PRODUCT: ${{ env.PRODUCT_NAME }}"

        '
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}
    - name: Check App Fair Catalog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: 'xcrun swift run -- fairtool catalog --verbose true --hub github.com/appfair
        --token "${{ secrets.GITHUB_TOKEN }}" -o -

        '
    - name: Check releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: 'gh release list

        '
    - name: 'Validate App Org: ${{ env.ORGNAME }}'
      run: xcrun swift run -- fairtool validate --verbose true --hub github.com/appfair
        --org "${{ env.ORGNAME }}" --token "${{ secrets.GITHUB_TOKEN }}" --project
        . --output -
    - name: Generate Icon
      run: xcrun swift run -- fairtool icon --org "${{ env.ORGNAME }}" --output Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png
        --output Assets.xcassets/AppIcon.appiconset/AppIcon-512.png || true
    - name: Test Swift Package
      if: github.event_name == 'push'
      run: xcrun swift test
    - name: Build macOS App
      run: "xcodebuild archive \\\n  -workspace \"App.xcworkspace\" \\\n  -configuration\
        \ Release \\\n  -scheme \"AppFairApp\" \\\n  -sdk \"macosx\" \\\n  -destination\
        \ 'platform=macOS' \\\n  -archivePath \"staging/${{ env.FAIR_APP_ARTIFACT\
        \ }}-macOS.xcarchive\" \\\n  CODE_SIGNING_REQUIRED=YES \\\n  CODE_SIGNING_ALLOWED=YES\
        \ \\\n  AD_HOC_CODE_SIGNING_ALLOWED=YES \\\n  CODE_SIGN_IDENTITY=\"-\" \\\n\
        \  PRODUCT_BUNDLE_IDENTIFIER=\"${{ env.BUNDLE_ID }}\" \\\n  FAIRAPP_PRODUCT_NAME=\"\
        ${{ env.PRODUCT_NAME }}\"\n\necho '<?xml version=\"1.0\" encoding=\"UTF-8\"\
        ?><!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\"\
        ><plist version=\"1.0\"><dict><key>method</key><string>mac-application</string><key>signingStyle</key><string>automatic</string><key>uploadBitcode</key><false/><key>compileBitcode</key><false/><key>uploadSymbols</key><false/></dict></plist>'\
        \ > \"staging/exportOptions.plist\"\n\nxcodebuild \\\n  -exportArchive \\\n\
        \  -archivePath \"staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.xcarchive\" \\\
        \n  -exportPath \"staging/\" \\\n  -exportOptionsPlist \"staging/exportOptions.plist\"\
        \n\ncodesign --verify --verbose=5 \"staging/${{ env.PRODUCT_NAME }}.app\"\n\
        codesign -dv --verbose=5 \"staging/${{ env.PRODUCT_NAME }}.app\"\ncodesign\
        \ -d --entitlements - \"staging/${{ env.PRODUCT_NAME }}.app\"\n\n# create\
        \ the zip file\nditto -c -k --sequesterRsrc --keepParent \"staging/${{ env.PRODUCT_NAME\
        \ }}.app\" \"staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip\"\n\n# show the\
        \ binary checksum\nls -la \"staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip\"\
        \nls -la \"staging/${{ env.PRODUCT_NAME }}.app/Contents/MacOS/\"*\nopenssl\
        \ sha256 \"staging/${{ env.PRODUCT_NAME }}.app/Contents/MacOS/\"*\nopenssl\
        \ sha256 \"staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip\"\n"
    - name: Notarize macOS App
      if: false
      run: xcrun notarytool submit "staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip"
        --password "${{ secrets.FAIR_NOTARIZATION_PASSWORD }}" --apple-id "${{ secrets.FAIR_NOTARIZATION_USERNAME
        }}" --team-id "${{ secrets.FAIR_NOTARIZATION_TEAMID }}" --progress --wait
    - name: Build iOS App
      run: "xcodebuild archive \\\n  -workspace \"App.xcworkspace\" \\\n  -configuration\
        \ Release \\\n  -scheme \"AppFairApp\" \\\n  -sdk \"iphoneos\" \\\n  -archivePath\
        \ \"staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.xcarchive\" \\\n  CODE_SIGNING_REQUIRED=NO\
        \ \\\n  CODE_SIGNING_ALLOWED=NO \\\n  AD_HOC_CODE_SIGNING_ALLOWED=YES \\\n\
        \  CODE_SIGN_IDENTITY=\"-\" \\\n  PRODUCT_BUNDLE_IDENTIFIER=\"${{ env.BUNDLE_ID\
        \ }}\" \\\n  FAIRAPP_PRODUCT_NAME=\"${{ env.PRODUCT_NAME }}\"\ncp -a \"staging/${{\
        \ env.FAIR_APP_ARTIFACT }}-iOS.xcarchive/Products/Applications\" \"staging/Payload\"\
        \nditto -c -k --sequesterRsrc --keepParent \"staging/Payload\" \"staging/${{\
        \ env.FAIR_APP_ARTIFACT }}-iOS.ipa\"\nrm -rf \"staging/Payload\" # cleanup\n\
        ls -la \"staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa\"\n"
    - name: Notarize iOS App
      if: false
      run: xcrun notarytool submit "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa"
        --password "${{ secrets.FAIR_NOTARIZATION_PASSWORD }}" --apple-id "${{ secrets.FAIR_NOTARIZATION_USERNAME
        }}" --team-id "${{ secrets.FAIR_NOTARIZATION_TEAMID }}" --progress --wait
    - name: Stage Release Metadata
      run: 'cp Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png staging/"${{ env.FAIR_APP_ARTIFACT
        }}.png"

        plutil -convert xml1 -r -o "staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.plist"
        -- "staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.xcarchive/Products/Applications/${{
        env.PRODUCT_NAME }}.app/Contents/Info.plist"

        plutil -convert xml1 -r -o "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.plist"
        -- "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.xcarchive/Products/Applications/${{
        env.PRODUCT_NAME }}.app/Info.plist"

        find "staging/" -type f

        '
    - name: Release App
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "echo \"Creating release: ${GITHUB_REF#refs/tags/}\"\ngh release create\
        \ \\\n  \"${GITHUB_REF#refs/tags/}\" \\\n  -- \\\n  Sandbox.entitlements \\\
        \n  Package.resolved \\\n  staging/${{ env.FAIR_APP_ARTIFACT }}.png \\\n \
        \ staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip \\\n  staging/${{ env.FAIR_APP_ARTIFACT\
        \ }}-macOS.plist \\\n  staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa \\\n \
        \ staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.plist\n"
  integrate_release:
    name: Integrate Release
    if: github.event_name == 'pull_request_target' && github.repository == 'appfair/App'
    runs-on: macos-latest
    timeout-minutes: 45
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0_beta.app/Contents/Developer
    steps:
    - name: Initialize fair-ground
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: 'echo "$GITHUB_CONTEXT"

        echo "PRTITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV

        echo "ORGNAME=${{ github.event.pull_request.head.user.login }}" >> $GITHUB_ENV

        echo "COMMITHASH=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

        echo "PRID=${{ github.event.pull_request.id }}" >> $GITHUB_ENV

        '
    - name: 'Configure App: ${{ env.ORGNAME }}'
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: 'echo "FAIR_APP_ARTIFACT=${{ env.ORGNAME }}" >> $GITHUB_ENV

        echo "PRODUCT_NAME=$(echo ${{ env.ORGNAME }} | tr ''-'' '' '')" >> $GITHUB_ENV

        echo "BUNDLE_ID=app.$(echo ${{ env.ORGNAME }})" >> $GITHUB_ENV

        echo "BUILDING PRODUCT: ${{ env.PRODUCT_NAME }}"

        '
    - name: Checkout Base Fairground
      uses: actions/checkout@v2
    - name: Checkout Integrate PR
      uses: actions/checkout@v2
      with:
        path: ReleasePR
        ref: ${{ env.COMMITHASH }}
        fetch-depth: 0
        submodules: false
    - name: Get PR commit message
      id: get_commit_message
      run: echo ::set-output name=commit_message::$(git -C ReleasePR log --format=%B
        -n 1 "${{ env.COMMITHASH }}")
    - name: Get PR commit tag
      id: get_commit_tag
      if: false
      run: echo ::set-output name=commit_message::$(git -C ReleasePR tag "${{ env.COMMITHASH
        }}")
    - name: Get app version
      id: get_app_version
      run: echo ::set-output name=app_version::$(/usr/libexec/PlistBuddy -c 'Print
        :CFBundleShortVersionString' ReleasePR/Info.plist)
    - name: 'Validate App-Org: ${{ env.ORGNAME }}'
      run: xcrun swift run -- fairtool validate --verbose true --hub github.com/appfair
        --org "${{ env.ORGNAME }}" --ref "${{ env.COMMITHASH }}" --integrationTitle
        "${{ env.PRTITLE }}" --maxsize $[1 * 1024 * 1024] --allow-from '.*.EDU' --allow-from
        '.*.appfair.net' --token "${{ secrets.GITHUB_TOKEN }}" --project ReleasePR
        --output -
    - name: Integrate PR
      if: startsWith(steps.get_commit_message.outputs.commit_message, 'release')
      run: 'rm -rf "staging/"

        mkdir "staging/"


        xcrun swift run -- fairtool merge --verbose true --hub github.com/appfair
        --org "${{ env.ORGNAME }}" --token "${{ secrets.GITHUB_TOKEN }}" --version-marker-dir
        "staging/" --project ReleasePR --output .


        xcrun swift package resolve

        xcrun swift run -- fairtool validate --hub github.com/appfair --org "${{ env.ORGNAME
        }}" --token "${{ secrets.GITHUB_TOKEN }}" --project .


        # next generate a default icon, if one doesn''t yet exist

        xcrun swift run -- fairtool icon --org "${{ env.ORGNAME }}" --output Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png
        --output Assets.xcassets/AppIcon.appiconset/AppIcon-512.png || true # tolerate
        failure

        file Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png


        #xcrun swift run -- fairtool edit --project . --hub github.com/appfair --bundle-id
        "${{ env.BUNDLE_ID }}" --display-name "${{ env.PRODUCT_NAME }}"


        cp -a .build/checkouts Dependencies

        tar cvzf "staging/${{ env.FAIR_APP_ARTIFACT }}-source.tgz" --exclude=''.git/''
        --exclude=''.build/'' --exclude=''staging/'' .

        rm -rf Dependencies

        '
    - name: 'Build macOS App: ${{ env.FAIR_APP_ARTIFACT }}-macOS.zip'
      run: "xcodebuild archive \\\n  -workspace \"App.xcworkspace\" \\\n  -configuration\
        \ Release \\\n  -scheme \"AppFairApp\" \\\n  -sdk \"macosx\" \\\n  -destination\
        \ \"platform=macOS\" \\\n  -archivePath \"staging/${{ env.FAIR_APP_ARTIFACT\
        \ }}-macOS.xcarchive\" \\\n  CODE_SIGNING_REQUIRED=YES \\\n  CODE_SIGNING_ALLOWED=YES\
        \ \\\n  AD_HOC_CODE_SIGNING_ALLOWED=YES \\\n  CODE_SIGN_IDENTITY=\"-\" \\\n\
        \  PRODUCT_BUNDLE_IDENTIFIER=\"${{ env.BUNDLE_ID }}\" \\\n  FAIRAPP_PRODUCT_NAME=\"\
        ${{ env.PRODUCT_NAME }}\"\n\necho '<?xml version=\"1.0\" encoding=\"UTF-8\"\
        ?><!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\"\
        ><plist version=\"1.0\"><dict><key>method</key><string>mac-application</string><key>signingStyle</key><string>automatic</string></dict></plist>'\
        \ > \"staging/exportOptions.plist\"\n\nxcodebuild \\\n  -exportArchive \\\n\
        \  -archivePath \"staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.xcarchive\" \\\
        \n  -exportPath \"staging/\" \\\n  -exportOptionsPlist \"staging/exportOptions.plist\"\
        \n\ncodesign --verify --verbose=5 \"staging/${{ env.PRODUCT_NAME }}.app\"\n\
        codesign -dv --verbose=5 \"staging/${{ env.PRODUCT_NAME }}.app\"\ncodesign\
        \ -d --entitlements - \"staging/${{ env.PRODUCT_NAME }}.app\"\nditto -c -k\
        \ --sequesterRsrc --keepParent \"staging/${{ env.PRODUCT_NAME }}.app\" \"\
        staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip\"\n\n# show the binary checksum\n\
        ls -la \"staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip\"\nls -la \"staging/${{\
        \ env.PRODUCT_NAME }}.app/Contents/MacOS/\"*\nopenssl sha256 \"staging/${{\
        \ env.PRODUCT_NAME }}.app/Contents/MacOS/\"*\nopenssl sha256 \"staging/${{\
        \ env.FAIR_APP_ARTIFACT }}-macOS.zip\"\n"
    - name: 'Build iOS App: ${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa'
      run: "xcodebuild archive \\\n  -workspace \"App.xcworkspace\" \\\n  -configuration\
        \ Release \\\n  -scheme \"AppFairApp\" \\\n  -sdk \"iphoneos\" \\\n  -archivePath\
        \ \"staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.xcarchive\" \\\n  CODE_SIGNING_REQUIRED=NO\
        \ \\\n  CODE_SIGNING_ALLOWED=NO \\\n  AD_HOC_CODE_SIGNING_ALLOWED=YES \\\n\
        \  CODE_SIGN_IDENTITY=\"-\" \\\n  PRODUCT_BUNDLE_IDENTIFIER=\"${{ env.BUNDLE_ID\
        \ }}\" \\\n  FAIRAPP_PRODUCT_NAME=\"${{ env.PRODUCT_NAME }}\"\ncp -a \"staging/${{\
        \ env.FAIR_APP_ARTIFACT }}-iOS.xcarchive/Products/Applications\" \"staging/Payload\"\
        \nditto -c -k --sequesterRsrc --keepParent \"staging/Payload\" \"staging/${{\
        \ env.FAIR_APP_ARTIFACT }}-iOS.ipa\"\nrm -rf \"staging/Payload\" # cleanup\n\
        ls -la \"staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.ipa\"\n"
    - name: Stage Release Metadata
      run: 'cp Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png staging/"${{ env.FAIR_APP_ARTIFACT
        }}.png"

        plutil -convert xml1 -r -o "staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.plist"
        -- "staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.xcarchive/Products/Applications/${{
        env.PRODUCT_NAME }}.app/Contents/Info.plist"

        plutil -convert xml1 -r -o "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.plist"
        -- "staging/${{ env.FAIR_APP_ARTIFACT }}-iOS.xcarchive/Products/Applications/${{
        env.PRODUCT_NAME }}.app/Info.plist"

        find "staging/" -type f

        '
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: staging
    - name: Generate fairseal
      env:
        GITHUB_TOKEN: ${{ secrets.APP_FAIR_BOT_TOKEN }}
      run: "# where we place the untrusted artifact\nmkdir -p UNTRUSTED/\n\n# build\
        \ the URL for the GitHub download artifact\nZIPURL=\"https://github.com/${{\
        \ env.ORGNAME }}/App/releases/download/${{ steps.get_app_version.outputs.app_version\
        \ }}/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip\" \n\necho \"Downloading: $ZIPURL\"\
        \n\n# retry a few times in case the head repository is still building\ncurl\
        \ --retry 10 --retry-all-errors -fsSL -o \"UNTRUSTED/${{ env.FAIR_APP_ARTIFACT\
        \ }}-macOS.zip\" \"$ZIPURL\"\n\nls -la \"staging/${{ env.FAIR_APP_ARTIFACT\
        \ }}-macOS.zip\" \nditto -xk \"staging/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip\"\
        \ fairseal/extracts/macOS/trusted/\n\nls -la \"UNTRUSTED/${{ env.FAIR_APP_ARTIFACT\
        \ }}-macOS.zip\"\nditto -xk \"UNTRUSTED/${{ env.FAIR_APP_ARTIFACT }}-macOS.zip\"\
        \ fairseal/extracts/macOS/UNTRUSTED/\n\n# peek at the different binaries\n\
        ls -la fairseal/extracts/macOS/trusted/*.app/Contents/MacOS/ fairseal/extracts/macOS/UNTRUSTED/*.app/Contents/MacOS/\n\
        \n# check that contents are identical, first excising\n# signatures to permit\
        \ custom signing & notarization\n# the actual diffing will be done by the\
        \ fairtool; this is just for diagnostics\ndiff -r fairseal/extracts/macOS/trusted\
        \ fairseal/extracts/macOS/UNTRUSTED || echo \"WARNING: contents differ\"\n\
        \n\n# if the seals match, we indicate success by publishing\n# the SHA256\
        \ for the release's pull request;\n# client apps will use this hash to verify\
        \ that the untrusted\n# release artifact that is downloaded matches the release\n\
        # artifact that was created in the trusted environment\nxcrun swift run --\
        \ fairtool fairseal --verbose true --hub github.com/appfair --org \"${{ env.ORGNAME\
        \ }}\" --ref \"${{ env.COMMITHASH }}\" --trusted-artifact \"staging/${{ env.FAIR_APP_ARTIFACT\
        \ }}-macOS.zip\" --untrusted-artifact \"UNTRUSTED/${{ env.FAIR_APP_ARTIFACT\
        \ }}-macOS.zip\" --artifact-url \"$ZIPURL\" --project . -o -\n"
    - name: Publish App Fair Catalog
      env:
        GITHUB_TOKEN: ${{ secrets.APP_FAIR_BOT_TOKEN }}
      run: 'gh workflow --repo appfair/appfair.github.io run "catalog.yml"

        '
